### ISSUE TITLE
EVER marketing strategy

### ISSUE THREAD

**Issue by EVER2d** [everscale-org/bounties#11]
**Is your feature request related to a problem? Please describe.**
It looks like we have a problem with a product development. Not a code, but product at all. It is not a decentralisation problem, but just a task we can fulfill

**Describe the solution you'd like**
Revise marketing. 
First of all, an analysis of all available data is needed, this will require the participation of the entire community. Even if these data are not too impressive. The results would be nice to discuss with Initials. 
Then, we must create closed working groups. At least 1. Groups should include not only developers - also marketers, sociologists, economists. Group proposals can be processed according to all bureaucratic procedures in MainGov.

...
PROFIT!!!111

**Describe alternatives you've considered**
Can wait, maybe it will happen randomly, before we reach the bottom

**Additional context**

Budget: 0 EVER

**Comment by eternalflow** [comment]
@EVER2d the DeFi Alliance already has groups for marketing and business development

Please contact me in telegram (https://t.me/isheldon) if you want to join
