### ISSUE TITLE
List of all TVM opcodes

### ISSUE THREAD

**Issue by cryshado** [everscale-org/bounties#32]
## Brief Introduction

This proposal aims to collect all TVM opcodes, including new ones from Everscale implementation, and generate a comprehensive CSV table with descriptions. The script for code generation in a markdown table will automate the process of updating the TVM opcode reference, saving time and effort. The resulting CSV table and markdown table will be useful for developers working on TVM projects, enabling them to quickly and easily reference all TVM opcodes and their descriptions, and the pull request to the documentation with the codegen pipeline will improve the overall quality of the TVM documentation, making it more  user-friendly.

Useful Materials
- [tvm.pdf](https://ton.org/tvm.pdf) with initial opcodes
- [instructions.csv](https://github.com/ton-blockchain/docs/blob/master/docs/smart-contracts/tvm-instructions/instructions.csv) from ton blockchain
- [TVM Extended Instructions](https://tonlabs.notion.site/tonlabs/TVM-Extended-Instructions-f22fb9a10bec4f8cadd9757e7d6df51d) (it is necessary to actualize)
- everscale-org/docs#255 issue
- https://docs.everscale.network/arch/tvm

## Goals

TVM Opcodes Table with Everscale Implementation:

- Collect all TVM opcodes with descriptions in a CSV table
- Add all new TVM opcodes from Everscale implementation
- Develop a script for code generation in a markdown table
- Open a new pull request to [docs](https://github.com/everscale-org/docs) with codegen pipeline  

The CSV table must contain the following fields:

| param         | description                                     |
| ----------- | ------------------------------------------------|
| `name`       | basic name 
| `alias`        | possible synonyms to the name
| `opcode`   | hexadecimal representation with arguments
| `category` | category of a specific operation
| `tvm_asm`| representation in tvm assembler with parameters
| `fift_asm`  | representation in fift assembler with parameters
| `stack`      | stack effects
| `gas`         | gas consumption
| `tlb`           | TL-B scheme for a specific operation and its parameters
| `desc`       | basic description

(the table can be expanded with other columns)

## What's the result

CSV table with all initial and Everscale implementation TVM opcodes. Pull request to [docs](https://github.com/everscale-org/docs) <br> with codegen pipeline, that can perform markdown table with all TVM opcodes from CSV table. 

## Reward (from [@everscale-org](https://github.com/everscale-org))

300 USDT in EVER base reward
50 USDT in EVER extra reward if the task is completed in less than 7 days

**Comment by cryshado** [comment]
@BorisI @elasticLove1 this proposal  needs your attention, thank you

**Comment by Dhruv245** [comment]
Hi, I would love to apply for this. I will complete the bounty in 2-3 hours. I am thinking of a bounty of $500 in TBD.

**Comment by cryshado** [comment]
> Hi, I would love to apply for this. I will complete the bounty in 2-3 hours. I am thinking of a bounty of $500

Sorry, we are not sure of your qualifications based on your past posts. We're very sorry, but we can't assign you

**Comment by ilyar** [comment]
:8ball:

**Comment by cryshado** [comment]
🎱

**Comment by eternalflow** [comment]
🎱 (which means that i support this bounty)

**Comment by kokkekpek** [comment]
Ready to get this task

**Comment by cryshado** [comment]
@kokkekpek Good luck! Remember to occasionally update us on your current progress by writing here

**Comment by Dhruv245** [comment]
Hi, Have completed the bounty. If you want, I can send the code

**Comment by kokkekpek** [comment]
> @kokkekpek Good luck! Remember to occasionally update us on your current progress by writing here

Have no time to do this

**Comment by cryshado** [comment]
> > @kokkekpek Good luck! Remember to occasionally update us on your current progress by writing here
> 
> Have no time to do this

Ok, no problem, I'll take you off the assignment. We'd love to see you in future :)

**Comment by ChainbrosTech** [comment]
Hi, I want to apply for this. Can you please tell me how?

**Comment by ChainbrosTech** [comment]
[goal3.zip](https://github.com/everscale-org/bounties/files/11331701/goal3.zip)

**Comment by ilyar** [comment]
@brymut Good luck! Remember to occasionally update us on your current progress by writing here

**Comment by brymut** [comment]
Quick update @ilyar , I have a created a WIP in progress PR here: https://github.com/everscale-org/docs/pull/326. Will update this comment by tomorrow with a full description of what I've been able to do, what I have left and what I need help with. Thanks.

**Comment by cryshado** [comment]
@brymut excellent! But please see https://github.com/tonlabs/ever-vm to specify stack effects, gas consumption for new opcodes, and also see https://github.com/tonlabs/ever-assembler to specify TVM ASM representation.

**Comment by ilyar** [comment]
@brymut How are things? Please update us on your status and plans, as we haven't heard from you in a while.

**Comment by ilyar** [comment]
https://dorahacks.io/daobounty/302

**Comment by gadillacer** [comment]
@ilyar Willing to take on this quest.

**Comment by gadillacer** [comment]
@cryshado @ilyar Hello, can you guys suggest how I can run the gas tests inside [ever-vm](https://github.com/tonlabs/ever-vm) repo? It will help a lot.

**Comment by ilyar** [comment]
@gadillacer  Currently, there is no straightforward way to do this. I will try to clarify and inform you later. In the meantime, you can use gas consumption values from the existing list in the related project (https://docs.ton.org/learn/tvm-instructions/instructions). Leave instructions blank if they are not available there. Hopefully, we will be able to fill them based on the information we obtain later.

**Comment by elasticLove1** [comment]
You can use ever-sdk (it has executor(VM is a part of executor)as a dependency) https://docs.everos.dev/ever-sdk/guides/work_with_contracts/estimate_fees  @gadillacer

**Comment by gadillacer** [comment]
Hello @ilyar, I'm still on my way to figuring out how stacks worked. 

By the way, I've just created a [PR](https://github.com/everscale-org/docs/pull/342).
Will update it with more information soon! Thanks

**Comment by gadillacer** [comment]
> Got my [PR](https://github.com/everscale-org/docs/pull/342)'s description updated. You can take a look at it now @ilyar @cryshado @elasticLove1

Check again, please.
Gonna move to official PR if everything's ok.

**Comment by ilyar** [comment]
@gadillacer https://github.com/everscale-org/docs/pull/342#pullrequestreview-1458517149

**Comment by ilyar** [comment]
Period for bounty extended upto 2023/05/19-2023/06/19 
https://dorahacks.io/daobounty/302

**Comment by gadillacer** [comment]
@ilyar Hi there! 
I'm interested in picking up this issue again, which I had been unassigned three weeks ago. It seems like finding a suitable candidate for this task has been challenging for you guys.

To better understand the difficulty level, I have five questions that I hope you can answer. By doing so, it will not only assist me in completing the task, but it will also provide valuable insights for future candidates. 

1. Can you provide more exact details about the additional column representing (gas effects? or additional information?)
2. Regarding the "Main network & Gosh" categorization in the markdown file, could you please clarify what it entails or how it should be implemented?
3. Is there a specific reason for using NPM instead of Python? Could you explain the desired final flow for this task? Is my current PR's Github Action okay?
4. Could you explain how the gas check should be performed in the "ever-vm"?
5. The task involving TVM assembler check-in codes seems quite challenging. Have you attempted it, or would you like me to ask for help in the "ever-assembler" repository?

Lastly, it would be helpful to know the expected or desired complete outcome for this task. Could you please provide more information about it?

Looking forward to your response!

**Comment by ilyar** [comment]
@gadillacer see Reference in https://github.com/everscale-org/docs/issues/255

**Comment by ilyar** [comment]
@gadillacer
 > Is there a specific reason for using NPM instead of Python? Could you explain the desired final flow for this task? Is my current PR's Github Action okay?
 
 Firstly, it is possible, and the main goal is to complicate the current stack and not complicate the build process
