### ISSUE TITLE
Everscale GraphQL code generatoration guide 

### ISSUE THREAD

**Issue by cryshado** [everscale-org/bounties#33]
### Brief Introduction

This proposal aims to inform developers about Everscale GraphQL and provide them with a detailed guide with step-by-step examples in TypeScript and GraphQL code generation. The guide will be delivered as a repository and included in the official documentation docs.everscale.network, with examples that are detailed, replicable, and understandable for most of the community developers. By providing developers with a comprehensive understanding of Everscale GraphQL, we hope to motivate them to leverage its capabilities and improve their application development process. The examples provided will also help developers to understand how to accept payments on their own backend, which is a valuable use case for many applications. With this proposal, we aim to empower developers to develop innovative and efficient applications with Everscale GraphQL.

Useful Materials
- [evercloud web site](https://www.evercloud.dev/)
- [evercloud docs](https://docs.evercloud.dev/)

### Goals

- Inform the developers what evercloud is graphql (what is it, how it works, how to get an auth token e.t.c.)
- Provide a detailed step-by-step guide with examples in TypeScript and GraphQL code generatoration
- Deliver these guide as a repository, which will later be included in the official documentation

Examples must consider a situation where a service (e.g., an exchange) wants to accept payments on its own backend. 
Examples must be detailed, replicable and understandable for most of community developers

### What's the result

- github repository with "Everscale GraphQL code generatoration step-by-step guide"

### Reward

250 USDT in EVER base reward (from @everscale-org)
50 USDT in EVER extra reward if the task is completed in less than 10 days

**Comment by cryshado** [comment]
@cyberiagod Good luck! Remember to occasionally update us on your current progress by writing here

**Comment by pizza-777** [comment]
Maybe should add an additional contest-battle for the most creative query? And the most interesting results include to the docs.

**Comment by cryshado** [comment]
> Maybe should add an additional contest-battle for the most creative query? And the most interesting results include to the docs.

@pizza-777 bounties != contests. We'll analyze the result of the current performer, and if it isn't of satisfactory quality, the result will be rejected, and the task will most likely get back to the `looking` status. 

We have also already contacted @cyberiagod and are waiting for the first public results or news in a few days

**Comment by cryshado** [comment]
@cyberiagod We're sorry. Our committee has decided that you aren't competent enough to perform this task

**Comment by pizza-777** [comment]
I have created [some scaffold](https://github.com/pizza-777/everscale-graphQL) for this bounty. May I try to complete it?

**Comment by cryshado** [comment]
@pizza-777 Hello! Thank you for taking the initiative to work on this issue. 
We are impressed that you have already begun work on this task, that's admirable! 

I just wanted to confirm if you have understood the task completely. Apart from writing the code, the task also requires the creation of a detailed guide for new developers. Will you have a chance to work on that as well? If not, please let me know and I will be happy to provide you with any additional information or support you may need.

Thank you again for your initiative, we will be eagerly awaiting your feedback!

**Comment by Dhruv245** [comment]
Hey would love to apply for the bounty

**Comment by Dhruv245** [comment]
Hi, can you please approve. So that I can start

**Comment by pizza-777** [comment]
@Dhruv245 you can do. But wait for @cryshado approving.

**Comment by Dhruv245** [comment]
Hi, I would just send the docs that you require

**Comment by Dhruv245** [comment]
**Everscale GraphQL Docs**

To obtain an auth token for Everscale GraphQL:
First, you need to create an account on Everscale's website by going to https://www.evercloud.dev/ Once you've created your account, navigate to the "API" section of the Everscale dashboard. Here, you'll find your API key and secret key. You'll need to use your API key and secret key to obtain an auth token.

```
import axios from 'axios';
const API_URL = 'https://api.everscale.network/v1';
const auth = {
username: 'YOUR_API_KEY', password: 'YOUR_SECRET_KEY',
};
const getToken = async () => { try {
const response = await axios.post(`${API_URL}/auth/token`, {}, { auth }); const token = response.data.token;
return token;
} catch (error) { console.error(error);
} };
export default getToken;

```

Replace "YOUR_API_KEY" and "YOUR_SECRET_KEY" with your actual API and secret keys. This code example will send a POST request to the Everscale GraphQL API to obtain an auth token. The API will respond with a JSON object that contains the token. You can then use this token to authenticate your requests to the Everscale GraphQL API. Once you've obtained an auth token, you can include it in your HTTP headers using the "Authorization" field.
 
```

 const headers = {
Authorization: `Bearer ${token}`,
};
```

Now we can use the Everscale GraphQL API to create and query data


**Backend server with TypeScript and GraphQL :**

```

import { ApolloServer, gql } from 'apollo-server';
const typeDefs = gql` type Query {
hello: String }
`;
const resolvers = { Query: {
hello: () => 'Hello world!', },
};
const server = new ApolloServer({ typeDefs, resolvers });
server.listen().then(({ url }) => { console.log(`Server ready at ${url}`);
});

```

**schema for your GraphQL API :**
```

type Payment {
id: ID!
amount: Float! currency: String! description: String!
}
type Mutation {
createPayment(amount: Float!, currency: String!, description: String!): Payment!
}
```

**API Call**


```

import axios from 'axios';
const API_URL = 'https://api.everscale.network/v1';
const auth = {
username: 'YOUR_API_KEY', password: 'YOUR_SECRET_KEY',
};
const createPayment = async (token: string, amount: number, currency: string, description: string) => {
const headers = {
Authorization: `Bearer ${token}`,
};
const query = `
mutation CreatePayment($amount: Float!, $currency: String!, $description: String!) {
createPayment(amount: $amount, currency: $currency, description: $description) { id
amount currency description
} }
`;
const variables = { amount, currency, description,
};
try {
const response = await axios.post(API_URL, { query, variables }, { headers }); return response.data.data.createPayment;
} catch (error) { console.error(error);

} };
export default createPayment;

```

**Comment by pizza-777** [comment]
:smile:  Sometimes chatGPT can be very helpful. But not always.

**Comment by Dhruv245** [comment]
Chatgpt was used for checking how to proceed, not for coding

**Comment by cryshado** [comment]
@Dhruv245 we reviewed your message, sorry we can't assign you for this task

**Comment by Dhruv245** [comment]
Sorry for the late reply. I had some fever, took me a lot of time to recover. 
I think I copy - pasted the wrong code snippet
Sending the actual tested one.

**Comment by Dhruv245** [comment]
**How to use Evercloud APIs**

For that first we need the API key and API secret from Evercloud platform. To get the both, we need to follow these steps: 

**Step 1**
Go to Evercloud dashboard by simply clicking on the following link: https://dashboard.evercloud.dev/
 You will be redirected to this page
Simply enter your details and create your account.

**Step 2**
Once you have created an Account, you will be redirected to you Evercloud Dashboard. You will see an interface
Click to create Add project button from the side bar and enter the name of the project you want to create.


**Step 3**
Once you have a project, click on the Project Name that you created from the sidebar.
You will see dashboard where you can see your graphQL endpoints that you can use to query the data for your application.

**Step 4**
Now go to the security sections from the navigation bar and you will see the page like this 
There are your API keys and API secret that you would require accessing the data through graphQL endpoints.
Copy both of them and save them somewhere safe in your code (use .env file for that in nodeJs project).

**Step 5**
Now again move back to endpoints and click on the pink button as you see in the image below:
You will be redirected to a page, it is your personal graphQL playground that you can use to play with queries and access the data without needing anything else.
All you have to do is write graphQL query in the playground and start playing with the data.

This is your personal graphQL playground that you can use to play with queries and access the data without needing anything else.
All you have to do is write graphQL query in the playground and start playing with the data.

**Example Query**

Let’s create an example query and access the data in our graphQL playground. We will query the transactions data from the blockchain. And for that this is the query we have to write:

```
query GetBlockData{
  blockchain{
    transactions{
      pageInfo{
        endCursor
      }
      edges{
        cursor
        node{
          id
          block_id
          status_name
        }
      }
    }
  }
}

```
 Copy the query and paste it in your graphQL playground. But this is not it. We need to provide the playground our API key to fetch the data and this is how we will do this.

Setting API key in playground
In your playground you will see a tab in the bottom:

Click on it and go to HTTP HEADERS and write this in line in the tab
```
{     "Authorization" : "Bearer <API key>" }
```
And you are good to go.
Then simply click on the run button on the playground and you will see the data on right side

**Comment by Dhruv245** [comment]
I can also share the screenshots if you require.

**Comment by leetdev** [comment]
@ilyar certainly!

I will create a repository for Everscale GraphQL code generatoration documentation, including introduction, step-by-step guide for getting started, and examples. I can complete this task in less than 10 days.

To add to it, I will of course follow the detailed instructions in the description, and the overall style of Everscale docs as much as possible. I will start today, and in reality, don't expect it to take longer than a few days.

**Comment by leetdev** [comment]
@ilyar I have completed the guide: https://github.com/leetdev/everscale-graphql

Note that I was going to create a more comprehensive example for accepting payments on the backend, but then I found [this demo](https://github.com/tonlabs/sdk-samples/tree/master/demo/exchange) which already has all that work done, so I figured why reinvent the wheel, and just linked to it in the doc. Hopefully that's all right.

The code examples are all tested using the setup in the examples folder.

Note, that even though a TypeScript setup was used, no actual TS code was used, and the code is fully JavaScript compatible. I figured it would make the examples more accessible, since not every developer wants to use TypeScript.

I have submitted work on Gitcoin, and provided my Everscale account address. A swift payout would be greatly appreciated.

**Comment by ilyar** [comment]
@leetdev You've done a great job reviewing the existing materials. Indeed, there are examples of the current task in one form or another, while the current goal is to update these examples and create working routes. Please note that your result does not include the use of code generation based on the GraphQL schema. When finalizing the result, duplicate the final description to a page in this documentation https://docs.everscale.network/. To do this, copy your description to the file https://github.com/everscale-org/docs/blob/main/src/develop/payment.md, which will create a page at https://docs.everscale.network/develop/payment. Use the markup examples from https://docs.everscale.network/develop/tutorial/everdev-sc/#configure-giver and https://github.com/everscale-org/docs/blob/main/src/develop/tutorial/everdev-sc.md?plain=1#L53-L86 for the various options. As an extended example, provide a link to the fork https://github.com/everscale-contest/everscale-graphql.

**Comment by ilyar** [comment]
@leetdev How are things? Please update us on your status and plans, as we haven't heard from you in a while. We plan to start looking for a new candidate tomorrow if we don't hear from you.

**Comment by leetdev** [comment]
@ilyar My apologies, I was having some health issues past few days and forgot to respond.

I misunderstood the part about code generation. I will modify the documentation accordingly tomorrow.

**Comment by leetdev** [comment]
@ilyar I have to apologize again for the delay, my health took a turn to the worse and I was unable to get any work at all done for several days this week. In addition, implementing the code generator was a bit more complicated than I expected, and took some research to complete. I also rewrote huge chunks of the guide because of my initial misunderstandings. It should be much better now.

I've created a PR in the docs repository: https://github.com/everscale-org/docs/pull/331

Please take a look ASAP and let me know if you need anything else. I would really appreciate it if the bounty could be paid out today, or some time tomorrow at the latest.

**Comment by leetdev** [comment]
Hello, any chance of getting the bounty paid out today?

Preferred payment method would be WEVER on BSC, my address is: `0x13376DAd779CC1783C52F304B0c58710960Cddbb`
Alternatively, native token on Everscale: `0:d5820c69148dadca6f3e6efbc4b4d2ead42f9217b8b338dd55019aa5e6c3cf23`

@ilyar @cryshado

**Comment by cryshado** [comment]
@leetdev Thank you, your guide looks really good! I left some comments at everscale-org/docs#331, please consider them so we can continue the process. After these changes we will be able to accept the PR and send bounty to your wallet.

**Comment by ilyar** [comment]
Hi, @leetdev! I sent 2 ever ([trx](https://everscan.io/messages/380810cdc0fe508803e1a94a822cbe7bc43386d23b5e26ba0f9b375f6abafbb9)) to your Everscale address `0:d5820c69148dadca6f3e6efbc4b4d2ead42f9217b8b338dd55019aa5e6c3cf23`, please confirm that you received it by sending 1 ever back. We need to make sure the address is really correct, then we'll send the rest of the amount of bounty. This is like "Satoshi Test". Thank you!

**Comment by leetdev** [comment]
@ilyar Done, [tx](https://everscan.io/transactions/e42ec308178457e18ecdc8503928e1edca974e1ccf2237b6cbc2621b7903a784)

**Comment by ilyar** [comment]
@leetdev Reward 250 USDT in 6400 EVER  [tx](https://everscan.io/messages/7c8e535d71af7cec8e9d55f341febe1faf64848e77582d8814e225c5e4952eed)

**Comment by ilyar** [comment]
**result:** https://docs.everscale.network/develop/payment
