### ISSUE TITLE
GraphQL based blockchain explorer for developers 

### ISSUE THREAD

**Issue by cryshado** [everscale-org/bounties#38]
### Brief Introduction

Everscale's blockchain ecosystem is currently lacking a developer-oriented blockchain explorer, which presents an opportunity for the creation of a web application that can display information on blocks and transactions, construct message graphs, parse and name fields in accordance with TL-B schemas, and provide detailed technical information. This project would provide immense value to developers seeking to understand the inner workings of Everscale's blockchain, and would be an essential tool in the ecosystem. The creation of such an explorer would not only enhance the capabilities of the Everscale blockchain, but would also offer an exciting challenge for developers and reviewers seeking to take on this task.

### Goals

Implement open-source blockchain explorer, which must:
- use [evercloud.dev](https://www.evercloud.dev/) graphql or [everspace.center](https://everspace.center/)
- have an user friendly and modern interface at all
- have an interface for switching networks and 
- an easy way to add new networks represented in evercloud
- ability to display a graph (as in [ton.cx](https://ton.cx/))
- name and display fields according to TL-B
- implement basic explorer functionality
- display extended informations about all phases
- display current network load (TPS and e.t.c.)
- display recent transactions and blocks
- display tvm disassembled code

All source code must be licensed and distributed 
under the open source GPLv3 or AGPLv3 license

References: [ton.cx](https://ton.cx/), [dton.io](https://dton.io/), [tonwhales](https://tonwhales.com/en/explorer), [toncoin.org](https://explorer.toncoin.org/)

This blockchain explorer must not use its own server side backend. Blockchain messages must be displayed in the same visual blocks of transactions, for example as in [ton.cx](https://ton.cx/) or [tonwhales](https://tonwhales.com/en/explorer)

### What's the result

Github repository with blockchain explorer open-source code licensed and distributed under the open source GPLv3 or AGPLv3 license. Instructions for setup, build, and launch this project in `README.md` file. 

### Reward

4,000.00 USD base reward 
1,000.00 USD extra reward if the task is completed in less than 45 days

**Comment by ChainbrosTech** [comment]
Hi, Could I appy for this?

**Comment by pyAndr3w** [comment]
I am ready to begin the task.

**Comment by pyAndr3w** [comment]
@cryshado, @ilyar
