### ISSUE TITLE
Content creator Contest [PROPOSAL]

### ISSUE THREAD

**Issue by gregoricordova** [everscale-org/bounties#41]
I think that the project is undervalued in many regions of the planet because marketing campaigns have not been carried out that lead to greater mass adoption.  A few days ago I was talking with a member of the broxus team about creating more campaigns like quizzes, AMAs, etc, and I think my idea was heard.  In addition to that, it would be nice to launch a content creation contest on different platforms, such as twitter, YouTube, or websites so that users can create educational content about everscale and at the same time earn a certain amount of ever tokens.  This will attract the attention of influencers and the project will have more presence on the networks, which is something that is currently very important to attract people's attention.

@gregoricordova

**Comment by ilyar** [comment]
For these purposes, this proposal https://everdao.net/governance/proposals/108 is currently being discussed, I think the authors are working on a more understandable plan so that there are chances to make it a reality
