### ISSUE TITLE
A big socially important product made by the Everscale community! Let's choose the idea of the product to develop it together. 

### ISSUE THREAD

**Issue by timcom-pro** [everscale-org/bounties#42]
### Brief Introduction

The proposal is based on the following hypothesis: 
People say we need "marketing", meaning advertising, PR and promotion. All this is some sort of explanation to people that technology is good. But spending energy here when there are few actual use cases is questionable. It is more effective to invest in implementing useful use cases for people first, and then this result will make the best "marketing" on its own (through feedbacks, social networks, and media).

Problem: Since the Subgovernances system was abolished in Everscale, the project has gained many things, including b-2-b orientation, but lost something important - community cohesion. A decentralized model. 

Solution: What needs to be done to strengthen the project now? Strengthen its community as one of the main driving forces. What needs to be done for this? Conduct quizzes, post publications, distribute airdrops? All of this will be ineffective without use cases. 

Since the Everscale blockchain is potentially ready for large-scale solutions, it is only necessary to choose several decisions and implement them. We can start with ONE that the community will focus on in the near future.

### Goals

What I suggest: 
To announce a contest for a specific product based on Everscale, with the community as creator. Everscale developers will be involved in the tasks of the technical side. We have influencers, analytics gurus and so on. And new people joining the network will know that they can get tokens by bringing value to the specific project they work on. It is much clearer to work on a specific project rather than on the promotion of technology which can process "many transactions per second", isn't it? It's time to implement specific use cases for this technology.

Each community member can propose the idea for the product. It could be, for example: 
- A global food delivery service on the blockchain
- A global taxi service on the blockchain
- A true charitable organization
- A blockchain version of the Earth planet 
- The task in the Space sphere (hello to Elon Musk)
Anything you like and believe this world needs in.

3 conditions: 
1) The project must be implemented using Everscale technology
2) The project must be large-scale and socially important (after all, technologies must improve our life, right?)
3) The project will be implemented by the community

### What's the result

A big socially important product made by blockchain community! And once it is successfully implemented, there will be no need for hype or expensive "marketing". Millions of people will rightly learn about Everscale and come here to work on the next products. (Of course, marketing work will also be important in turn). 

So, first, let's make another proposal to choose the product.

After detailed analysis, the community itself will decide how much tokens is needed for the initial phase of work on the project, what units will be created, and how work will be organized in general. Everscale teamwork might be strong using brains ))

Resume: 
Community-driven blockchain should be developed by the strong community for the benefit of people - this seems organic. 

We have excellent teams of developers. They are people to rely on. The only thing missing is community driven use cases.. and users. Let's start by focusing on a useful and understandable product, and people will join this work. As a result of implementation, millions of people and investments will likely come to the Everscale ecosystem.

### Reward

I choose EVER. And my prize can be used as a prize for the product contest winner (to the author of the idea that the community decides to develop).

May the best idea win!)

**Comment by ilyar** [comment]
Thank you for the detailed description, but you essentially described in other words the very idea of the competition, which was previously proposed in the community to motivate the creation of useful tasks.

I don't see opportunities to turn this into a real task that can be implemented, how do you see it, you hold another contest....? What's your idea? The purpose of the competition initiated in the community was precisely to propose tasks that could be implemented.
