### ISSUE TITLE
Ready-to-use TypeScript libraries for working with NFTs

### ISSUE THREAD

**Issue by ilyar** [everscale-org/bounties#46]
Ready-to-use TypeScript libraries for working with NFTs (ownedItems, collections, collectionItems, indexHelper)

https://docs.everscale.network/standard/TIP-4

The current task is briefly described, and it can be solved in various ways. Please provide your vision of the solution, outline the work plan, estimate the required time to complete the plan, and suggest the expected reward. If you are unsure, you may leave this field blank.

**Comment by naftalimurgor** [comment]
Hello,
I'm ready to work on this, with the following itinerary:
Library written in TypeScript, that
- Works in the Browsers(React, Svelte, Vuejs applications) and Nodejs environments
- Querying On-Chain Token data
- Placing Orders for Tokens
- Transfering Tokens

ETA: Time span 1month
Approximate reward: $2500
