### ISSUE TITLE
Client-side library in Golang on top of JSON-RPC

### ISSUE THREAD

**Issue by ilyar** [everscale-org/bounties#48]
https://github.com/broxus/everscale-jrpc

The current task is briefly described, and it can be solved in various ways. Please provide your vision of the solution, outline the work plan, estimate the required time to complete the plan, and suggest the expected reward. If you are unsure, you may leave this field blank.

**Comment by cryshado** [comment]
Hi, @ilyar! I can take on this task, and finish it in 1-2 weeks and I think a reward of 2,000 USD would be adequate. My plans are to implement support for all current JRPC methods, that exist at the moment, a convenient client with its own context.

**Deliverables**

GitHub repository with Everscale JRPC Golang library and examples
