### ISSUE TITLE
nft lootbox (nft which mints random nfts when destroyed)

### ISSUE THREAD

**Issue by ilyar** [everscale-org/bounties#8]

**Comment by com-master** [comment]
Минтит нфт у самой себя или у какой то коллекции? Дестроится просто так или за деньги?

**Comment by eternalflow** [comment]
@com-master реализуй так, как считаешь это наиболее пригодным для будущей интеграции в проекты

цель этих задач - дать проектам которые заходят в экосистему набор примеров работающих решений которые они смогут себе забирать и менять

поэтому нюансы не так важны

**Comment by user090909** [comment]
Актуально еще?

**Comment by ilyar** [comment]
![image](https://user-images.githubusercontent.com/761285/175039344-c875efd9-e177-44f6-b432-891ca32f56a4.png)

https://www.youtube.com/watch?v=6F1L7XkviNg

**Comment by ilyar** [comment]
https://everscan.io/transactions/37b390c3c300be32d0b97b21c96c2dca3af3dfb9bceb2ed2a6dbe297577002a7
